### ISSUE TITLE
Always responding with 401 Unauthorized

### ISSUE THREAD

**Issue by iandees** [lpsinger/flask-twilio#1]
I have a simple Flask app set up and tested using Twilio + ngrok locally. When I flip `testing` off, the endpoint always responds with a `401 Unauthorized` to Twilio.

I have `SECRET_KEY` set to some random string, `TWILIO_ACCOUNT_SID` and `TWILIO_AUTH_TOKEN` correctly set (because I can make requests to the Twilio API), but it seems like the authorization wrapper in this library is doing something weird.

It looks like the wrapper is [checking for authorization headers](https://github.com/lpsinger/flask-twilio/blob/master/flask_twilio.py#L137-L146), with the username `twilio` and some password. What should the password be?

Assuming it can just be anything (as long as the username is `twilio`), I tried setting my webhook to `https://twilio:abcdefg@abcxyz.herokuapp.com/webhooks/sms.xml`. I can see Twilio making two requests (like [the docs say](https://www.twilio.com/docs/api/security#http-authentication), but the second request is still `401 Unauthorized`.

What am I missing?

**Comment by lpsinger** [comment]
The package [initiates the call using a password that is a random string, signed with itsdangerous](https://github.com/lpsinger/flask-twilio/blob/v0.0.1/flask_twilio.py#L188-L195). How long are you waiting from the time that you generate the twiml document and the time that you make the call? The signature [is only valid for 10 minutes](https://github.com/lpsinger/flask-twilio/blob/v0.0.1/flask_twilio.py#L137). (That timeout should probably be a configuration variable.)

**Comment by iandees** [comment]
I'm not using the library to make a call, I'm using it to handle SMS webhooks. I have the flask endpoint's URL in the Twilio configuration panel as the webhooks to send to when a new SMS is received.

**Comment by pranjut** [comment]
@iandees  have you solved the problem already? please share, I'm kind of stuck with the same problem.

**Comment by iandees** [comment]
@pranjut No, I never solved this. I ended up switching to stuff built up from [Twimlets](https://www.twilio.com/labs/twimlets).

**Comment by pranjut** [comment]
Thank @iandees
